### ISSUE TITLE
Add social login backend

### ISSUE THREAD

**Issue by aswinzz** [NJACKWinterOfCode/Backend#1]

**Comment by arunikayadav42** [comment]
I would like to take this up.

**Comment by arunikayadav42** [comment]
There is no requirements.txt file

**Comment by arunikayadav42** [comment]
Can I open an issue regarding the same?

**Comment by aswinzz** [comment]
Yes you can work on this and create a new issue

**Comment by arunikayadav42** [comment]
how do we get the password for the database?django.db.utils.OperationalError: fe_sendauth: no password supplied..I get this error while trying to run python manage.py runserver.

**Comment by aswinzz** [comment]
you should use postgresql and create a user and password and it should be added in settings.py

**Comment by arunikayadav42** [comment]
Do I need to follow the syntax of django 2+ or older django versions?Also there are no template files so do I need to build everything from scratch...how do I test the views?
