### ISSUE TITLE
Add endpoint for saving charts into backend

### ISSUE THREAD

**Issue by aswinzz** [NJACKWinterOfCode/Backend#3]

**Comment by arunikayadav42** [comment]
I would like to take up this issue...can you explain this issue a bit?

**Comment by aswinzz** [comment]
What actually happens is the needed data is send to the frontend and charts are made, so if the user wants to save the visualization for future purpose he can click on save which will save the current data which was fetched and can be used later.
so you will have to create a new table which will store the data similar to how it was send to the frontend.

**Comment by arunikayadav42** [comment]
I have made a pull request please review it.
